[pytest]
generate_report_on_test = True
markers =
    interview: mark a test as related to interview summaries
    keynote: mark a test as related to keynote summaries
    paper: mark a test as related to scientific paper summaries
    report: mark a test as related to report summaries
    book: mark a test as related to book summaries
    presentation: mark a test as related to presentation slides summaries
    performance: mark a test as related to performance comparison
    compare: mark a test as related to comparison between old and new summarizers
    compare_facts: mark a test as related to comparison between old and new summarizers
    compare_quotes: mark a test as related to comparison between old and new summarizers
    compare_sentiment: mark a test as related to comparison between old and new summarizers
